services:
  redis:
      image: redis:7-alpine
      container_name: dispatcharr_dev_redis
      ports:
        - 6379:6379

  dispatcharr:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        TIMESTAMP: "${TIMESTAMP:-}"
    image: ghcr.io/dispatcharr/dispatcharr:base
    container_name: dispatcharr_dev
    ports:
      - 5656:5656
      - 9191:9191
      - 8001:8001
    volumes:
      - ../:/app
      - dispatcharr_data:/data
    environment:
      - DISPATCHARR_ENV=dev
      - REDIS_HOST=redis
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DISPATCHARR_LOG_LEVEL=debug
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - dispatcharr_dev_pgadmin:/var/lib/pgadmin
    ports:
      - 8082:80

volumes:
  dispatcharr_dev_pgadmin:
  dispatcharr_data:
    external: true
    name: dispatcharr_dispatcharr_data
