services:
  dispatcharr:
    # build:
    #   context: ..
    #   dockerfile: docker/Dockerfile.alpine
    image: dispatcharr/dispatcharr
    container_name: dispatcharr
    ports:
      - 9191:9191
    volumes:
      - /home/ghost/code/Dispatcharr/docker/entrypoint.sh:/app/docker/entrypoint.sh
    #   - dispatcharr_db:/app/data/db
    environment:
      - DISPATCHARR_ENV=aio
      - REDIS_HOST=localhost
      - CELERY_BROKER_URL=redis://localhost:6379/0

volumes:
  dispatcharr_db:
